$('.owl-carousel').owlCarousel({
    loop:true,
    margin:16,
    nav:false,
    autoplay:true,
    dots:false,
    arrows:false,
    responsive:{
        1000:{
            items:3,
            nav:false,
        }
    }
})